"""init

Revision ID: 417ae449b0da
Revises: 
Create Date: 2026-06-14 14:55:54.184664
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417ae449b0da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='前端填写的展示名，也是MD文件名'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件简介'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='原始上传文件名'),
    sa.Column('source_format', sa.String(length=10), nullable=False, comment='pdf | docx | txt'),
    sa.Column('source_path', sa.String(length=512), nullable=False, comment='data/下的源文件路径'),
    sa.Column('md_path', sa.String(length=512), nullable=False, comment='uploads/public/下的MD文件路径'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='public | project'),
    sa.Column('size', sa.Integer(), nullable=False, comment='文件大小(bytes)'),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('projects')
    # ### end Alembic commands ###
